spring:
  datasource:
    url: jdbc:mysql://localhost:3306/sales?useTimeZone=true&serverTimeZone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 1234
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    properties:
      hibernate:
        show_sql: true
        format_sql: true

security:
  jwt:
    expiration: 30
    secretKey: secretKey

springdoc:
  swagger-ui:
    path: /swagger-ui.html

